# Translation mapping for untranslated compliance keys
# Format: key -> zh_translation
# For standard names: keep acronyms (FDA, CE, FCC, etc.), translate descriptive parts
# For descriptions: translate full sentences
# For actions: translate to imperative Chinese

mappings = {}

# ========== site.compliance (740 keys - standard names) ==========
# Pattern: Keep acronyms, translate descriptive words
compliance_map = {
    # USA
    "California Prop 65": "加州65号提案",
    "Prop 65": "65号提案",
    "Prop 65 Lead Cadmium Testing": "铅镉含量检测(65号提案)",
    "Prop 65 Garden Chemicals": "园艺化学品(65号提案)",
    "Prop 65 Luggage Materials": "箱包材质(65号提案)",
    "FDA 21 Cfr Part 820": "FDA 21 CFR 第820条",
    "FDA License To Operate": "FDA运营许可证",
    "FDA Food Facility Registration": "FDA食品设施注册",
    "FDA Food Establishment Registration": "FDA食品企业注册",
    "FDA Food Contact Materials": "FDA食品接触材料",
    "FDA Dietary Supplement Registration": "FDA膳食补充剂注册",
    "FDA Cosmetics Registration": "FDA化妆品注册",
    "FDA Medical Device Registration": "FDA医疗器械注册",
    "FDA Pet Food": "FDA宠物食品",
    "Cpsc Children S Product Certificate Cpc": "儿童产品证书(CPC)",
    "Cpsc Children S Product Certificate": "儿童产品证书",
    "Cpsc Children S Product Notice": "儿童产品通知",
    "Cpsc Children S Clothing": "儿童服装(CPSIA)",
    "Cpsc Children S Stationery": "儿童文具(CPSIA)",
    "Cpsc Children S Sports Equipment": "儿童运动器材(CPSIA)",
    "Cpsc Children S Books": "儿童书籍(CPSIA)",
    "Cpsc Pacifier Teether FDA": "奶嘴牙胶(FDA)",
    "Cpsc Traceability Label": "CPC追溯标签",
    "Cpsia Children S Books": "儿童书籍(CPSIA)",
    "Cpsia Children S Clothing": "儿童服装(CPSIA)",
    "Cpsia Children S Product Certificate": "儿童产品证书(CPSIA)",
    "Cpsia Children S Product Notice": "儿童产品通知(CPSIA)",
    "Cpsia Children S Sports Equipment": "儿童运动器材(CPSIA)",
    "Cpsia Children S Stationery": "儿童文具(CPSIA)",
    "ASTM F963 Toy Safety Standard": "ASTM F963 玩具安全标准",
    "ASTM Sports Equipment Standard": "ASTM 运动器材标准",
    "FTC Jewelry Labeling": "FTC 珠宝标签",
    "FTC Labeling Requirements": "FTC 标签要求",
    "FTC Textile Labeling": "FTC 纺织品标签",
    "Epa Pesticide Registration": "EPA 农药注册",
    "Dshea Compliance": "DSHEA 合规",
    "Nlea Nutrition Labeling": "NLEA 营养标签",
    "Tsa Lock Certification": "TSA 锁认证",
    "Sae Standard": "SAE 标准",
    "Tsa Lock Certification": "TSA 锁认证",
    
    # EU/UK
    "CE Marking": "CE 标志",
    "CE Marking Toys": "玩具CE标志",
    "CE Medical Device Certification": "医疗器械CE认证",
    "CE Children S Books": "儿童书籍CE",
    "CE Electronic Luggage": "电子箱包CE",
    "CE Mark Turkey": "土耳其CE标志",
    "EU Authorized Representative": "欧盟授权代表",
    "EU Authorized Representative Ec Rep": "欧盟授权代表(EC REP)",
    "EU Battery Regulation": "欧盟电池法规",
    "EU Nickel Release Testing": "欧盟镍释放检测",
    "EU Textile Labeling Regulation": "欧盟纺织品标签法规",
    "EU 10 2011 Food Contact Materials": "EU 10/2011 食品接触材料",
    "EU 1107 2009 Pesticides": "EU 1107/2009 农药",
    "EU 1223 2009 Cosmetics Regulation": "EU 1223/2009 化妆品法规",
    "EU 178 2002 Food Safety": "EU 178/2002 食品安全",
    "EU 1924 2006 Nutrition Labeling": "EU 1924/2006 营养标签",
    "EU 1223 2009 Cosmetics Regulation": "EU 1223/2009 化妆品法规",
    "EU Authorized Representative": "欧盟授权代表",
    "UK Authorized Representative": "英国授权代表",
    "UK RoHS": "英国RoHS",
    "UK Toy Safety Regulations": "英国玩具安全法规",
    "UKCA Mark": "UKCA 标志",
    "UKCA Toy Certification": "UKCA 玩具认证",
    "REACH Regulation": "REACH 法规",
    "REACH SVHC": "REACH SVHC(高度关注物质)",
    "REACH Heavy Metal Restrictions": "REACH 重金属限制",
    "REACH Ingredient Compliance": "REACH 成分合规",
    "REACH Luggage Materials": "REACH 箱包材质",
    "REACH Material Compliance": "REACH 材质合规",
    "REACH Printing Ink Safety": "REACH 印刷油墨安全",
    "REACH Garden Chemicals": "REACH 园艺化学品",
    "REACH Textiles": "REACH 纺织品",
    "REACH Material Compliance": "REACH 材质合规",
    "RoHS Directive": "RoHS 指令",
    "WEEE Directive": "WEEE 指令",
    "EN 71 Baby Products": "EN 71 婴幼儿用品",
    "EN 71 Children S Stationery": "EN 71 儿童文具",
    "EN 71 Full Testing": "EN 71 全面检测",
    "EN 1888 Baby Stroller Standard": "EN 1888 婴儿推车标准",
    "EN 13844 Sports Equipment": "EN 13844 运动器材",
    "Food Grade Contact Materials FDA EU 10 2011": "食品级接触材料(FDA EU 10/2011)",
    "Medical Device Regulation 2017 745": "医疗器械法规(EU)2017/745",
    "Mdr Medical Device Regulation": "MDR 医疗器械法规",
    "Gmp Iso 22716": "GMP ISO 22716",
    "Gmp Production Standard": "GMP 生产标准",
    "Fefana Pet Food": "FEFANA 宠物食品",
    "Eu Authorized Representative Ec Rep": "欧盟授权代表(EC REP)",
    
    # Germany
    "Lgv Rhdland": "莱茵河莱州(LGV Rheinland)",
    "Lab Tuv Rheinland Desc": "TUV莱茵实验室认证",
    
    # Japan
    "PSE Certification": "PSE 认证",
    "Telec Certification": "TELEC 认证",
    "Jis T 8101 Toy Safety Standard": "JIS T 8101 玩具安全标准",
    "Vcci Emc": "VCCI EMC",
    "Kcc Radio Approval": "KCC 无线电批准",
    "KC Mark": "KC 标志",
    "KC Toy Safety Kts 0052": "KC 玩具安全(KTS 0052)",
    "KC Auto Electronics": "KC 汽车电子",
    "KC Smart Luggage": "KC 智能箱包",
    "KC Mark Decor With Electronics": "带电子装饰KC标志",
    "K Eco Energy Label": "K-ECO 能源标签",
    "Korea Auto Electronic Components": "韩国汽车电子元件",
    "Korea Baby Food And Product Safety": "韩国婴幼儿食品及产品安全",
    "Korea Certification Mandatory Safety Certification": "韩国强制安全认证",
    "Korea Communications Commission Wireless Devices": "韩国通信委员会无线设备",
    "Korea Mandatory Toy Safety Certification": "韩国强制玩具安全认证",
    "Korea Ministry Of Food And Drug Safety Cosmetics": "韩国MFDS化妆品",
    "Korea Pet Food Safety Requirements": "韩国宠物食品安全要求",
    
    # Australia/NZ
    "As Nzs 8124 Toy Safety": "AS/NZS 8124 玩具安全",
    "Rcm Mark": "RCM 标志",
    "Eess Energy Registration": "EEESS 能源注册",
    "Adr": "ADR(澳驾规则)",
    "NZRC Electrical Consent": "NZRC 电气许可",
    "Medsafe Registration": "Medsafe 注册",
    
    # China
    "Ccc Certification": "CCC 认证",
    "China Rohs": "中国RoHS",
    "China Compulsory Certification": "中国强制性产品认证(CCC)",
    
    # India
    "BIS Certification": "BIS 认证",
    "BIS Baby Products": "BIS 婴幼儿用品",
    "BIS RoHS": "BIS RoHS",
    "BIS Toy Standard Is 9873": "BIS 玩具标准 IS 9873",
    "Bis Baby Products": "BIS 婴幼儿用品",
    "Bis RoHS": "BIS RoHS",
    "Bis Toy Standard Is 9873": "BIS 玩具标准 IS 9873",
    "Cdsco Cosmetic Rules": "CDSCO 化妆品法规",
    "Fssai Pet Food": "FSSAI 宠物食品",
    "Wireless Planning Commission Wireless Devices": "无线规划委员会无线设备",
    
    # Brazil
    "Anatel Certification": "ANATEL 认证",
    "Anvisa Cosmetic Notification": "ANVISA 化妆品备案",
    "Inmetro Certification": "INMETRO 认证",
    "Inmetro Baby Products": "INMETRO 婴幼儿用品",
    "Inmetro Glass Ceramic": "INMETRO 玻璃陶瓷",
    "Inmetro Sports Equipment": "INMETRO 运动器材",
    "Inmetro Wheeled Luggage": "INMETRO 拉杆箱",
    "Inmetro Auto Electronics": "INMETRO 汽车电子",
    
    # Southeast Asia
    "SiriM Safety Mark": "SIRIM 安全标志",
    "SiriM Toy Safety": "SIRIM 玩具安全",
    "Tisi Certification": "TISI 认证",
    "Tisi Toy Safety Tis 1347": "TISI 玩具安全 TIS 1347",
    "Sni Certification": "SNI 认证",
    "Sni Toy Safety": "SNI 玩具安全",
    "Bpom Food Cosmetic Registration": "BPOM 食品化妆品注册",
    "Bpom Food Registration": "BPOM 食品注册",
    "Bps Standard Mark": "BPS 标准标志",
    "Bps Toy Safety Pns 1363": "BPS 玩具安全 PNS 1363",
    "NEA Consumer Protection Toys": "NEA 消费者保护(玩具)",
    "NEA Cosmetic Notification": "NEA 化妆品备案",
    "NEA RF Compliance": "NEA RF合规",
    "IDA Safety Mark": "IDA 安全标志",
    "Mcmc Type Approval": "MCMC 型号批准",
    "Kominfo Registration": "Kominfo 注册",
    "Bps Standard Mark": "BPS 标准标志",
    "Bps Toy Safety Pns 1363": "BPS 玩具安全 PNS 1363",
    "Ntc Type Approval": "NTC 型号批准",
    
    # Middle East
    "Saso Saber Certification": "SASO SABER 认证",
    "Saso Toy Safety Saso Iso 8124": "SASO 玩具安全 ISO 8124",
    "Saso Decorative Products": "SASO 装饰产品",
    "Saso Energy Efficiency Eepo": "SASO 能效 EEPO",
    "Saso Luggage With Electronics": "带电子功能的箱包(SASO)",
    "Saso Precious Metal Marking": "SASO 贵金属标记",
    "Halal Certification SFDA": "清真认证(SFDA)",
    "SFDA Baby Food": "SFDA 婴幼儿食品",
    "SFDA Food Registration": "SFDA 食品注册",
    "Dubai Municipality Food Registration": "迪拜市政食品注册",
    "Dubai Municipality Gold Purity Testing": "迪拜市政黄金纯度检测",
    "Gso Labeling Standards": "GSO 标签标准",
    "Gulf Standardization Organization Labeling Arabic English": "海湾标准化组织标签(阿拉伯语/英语)",
    "Gulf Toy Safety Requirements": "海湾玩具安全要求",
    "ESMA Product Certification": "ESMA 产品认证",
    "ESMA Luggage With Electronics": "带电子功能的箱包(ESMA)",
    "ESMA Toy Safety Gso 2229": "ESMA 玩具安全 GSO 2229",
    "Emirates Authority For Standardization And Metrology Gulf Conformity Requirements": "阿联酋标准化计量局海湾合规要求",
    "Uae Telecommunications Authority Wireless Radio Devices": "阿联酋电信局无线设备",
    "Uae Requires Gold Purity Testing For Jewelry": "珠宝黄金纯度检测(UAE)",
    "Esma Product Certification": "ESMA 产品认证",
    "Esma Luggage With Electronics": "带电子功能的箱包(ESMA)",
    "Esma Toy Safety Gso 2229": "ESMA 玩具安全 GSO 2229",
    "Gso Labeling Standards": "GSO 标签标准",
    
    # Other Middle East
    "Koc Food Registration": "KOC 食品注册",
    "Koc Standards": "KOC 标准",
    "Mosa Standard Israel": "MOSA 以色列标准",
    
    # South America
    "Nom Certification": "NOM 认证",
    "Cofepris Cosmetic Registration": "COFEPRIS 化妆品注册",
    "Cofepris Registration": "COFEPRIS 注册",
    "Mexican Health Agency Cosmetics": "墨西哥卫生机构化妆品",
    "Mexican Health Agency Food Supplements Medical Devices": "墨西哥卫生机构膳食补充剂医疗器械",
    "Mexican Official Standards For Electronics Toys Packaging": "墨西哥电子产品玩具包装官方标准",
    "Cec Energy Efficiency": "加州能源委员会能效",
    "California Prop 65": "加州65号提案",
    
    # Europe other
    "Tse Certification": "TSE 认证",
    "Turkey Adopts Ce Marking For Many Categories": "土耳其采用CE标志(多类目)",
    "Turkish Standards Institute Mandatory Standards": "土耳其标准化研究所强制标准",
    
    # Africa
    "Sabs Mark": "SABS 标志",
    "South African Bureau Of Standards Mandatory For Electronics Toys Building Materials": "南非标准局(电子/玩具/建材强制)",
    "Icasa Type Approval": "ICASA 型号批准",
    "Soncap": "SONCAP",
    "Soncap Nafdac": "SONCAP/NAFDAC",
    
    # General
    "Energy Labeling": "能效标签",
    "Flammability Testing": "阻燃测试",
    "Flammability Testing Luggage": "箱包阻燃测试",
    "Lead Content Testing": "铅含量检测",
    "Suffocation Prevention Design": "防窒息设计",
    "Copyright Compliance": "版权合规",
    "Food Hygiene Law Painted Toys": "食品卫生法(彩绘玩具)",
    "Fsma Food Safety": "FSMA 食品安全",
    "Food Safety Modernization Act Compliance": "食品安全现代化法案合规",
    "Fta Textile Labeling": "FTC 纺织品标签",
    "Fta Jewelry Labeling": "FTC 珠宝标签",
    "Fta Labeling Requirements": "FTC 标签要求",
    "Insecticides Herbicides Fungicides Require Epa Registration": "杀虫剂/除草剂/杀菌剂需EPA注册",
    "Israeli Standards Institute Mandatory For Electronics Toys": "以色列标准局(电子/玩具强制)",
    "Japan Electromagnetic Compatibility Voluntary Certification Type B Equipment": "日本电磁兼容自愿认证(B类设备)",
    "Japanese Toy Safety Standard Including Physical Chemical And Electrical Testing": "日本玩具安全标准(物理/化学/电气测试)",
    "Jewelry Materials Must Comply With REACH Heavy Metal Restrictions": "珠宝材质需符合REACH重金属限制",
    "Jewelry May Contain Heavy Metals Like Lead Cadmium Requires Warning Label Or Compliance": "珠宝可能含铅/镉等重金属，需警告标签或合规",
    "Kitchenware May Contain Heavy Metals E G Cast Iron Pots": "厨具可能含重金属(如铸铁锅)",
    "Lithium Battery Products Must Comply With UL 2743 Safety Standard": "锂电池产品需符合UL 2743安全标准",
    "Luggage Materials May Contain Chemicals Requiring Warning": "箱包材质可能含需警告的化学物质",
    "Luggage Materials Must Comply With REACH": "箱包材质需符合REACH",
    "Luggage Must Pass Flammability Testing": "箱包需通过阻燃测试",
    "Luggage With Battery Electronics Requires SASO SABER Certification": "带电池电子功能的箱包需SASO SABER认证",
    "Luggage With Battery Requires ESMA Conformity Assessment": "带电池箱包需ESMA符合性评估",
    "Luggage With Usb Charging Or Other Electronic Features Requires CE Certification": "带USB充电等电子功能的箱包需CE认证",
    "Mandatory CE Certification For Medical Devices": "医疗器械强制CE认证",
    "Mandatory CE Certification For Toys Including Mechanical Flammability And Chemical Testing": "玩具强制CE认证(含机械/阻燃/化学测试)",
    "Mandatory Energy Efficiency Label": "强制能效标签",
    "Mandatory Energy Efficiency Labeling For Certain Electrical Appliances": "部分电器强制能效标签",
    "Mandatory For Children S Products Under 12 Testing By CPSC Accepted Laboratory": "12岁以下儿童产品需CPSC认可实验室检测",
    "Mandatory Halal Certification For Meat And Meat Products": "肉类及肉制品强制清真认证",
    "Mandatory Nutrition Facts Labeling": "强制营养成分标签",
    "Mandatory Safety Certification Mark For The EU Market Compliant With LVD EMC Directives": "欧盟市场安全认证标志(LVD/EMC指令)",
    "Mandatory Safety Certification Mark For The UK Market Replaces CE Except Northern Ireland": "英国市场安全认证标志(替代CE，北爱尔兰除外)",
    "Mandatory UK Toy Certification Replaces CE": "英国玩具认证替代CE",
    "Medical Device Quality Management System Regulation": "医疗器械质量管理体系法规",
    "Medical Devices And Health Products": "医疗器械和健康产品",
    "Medical Devices Must Register By Class I Ii Iii": "医疗器械按I/II/III类注册",
    "National Environment Agency Regulation For Wireless Rf Devices": "国家环境局无线RF设备法规",
    "National Telecommunications Commission Wireless Radio Devices": "国家电信委员会无线设备",
    "New Zealand Registration Certificate For Electrical Equipment": "新西兰电气设备注册证书",
    "Nickel Release From Skin Contact Jewelry Parts Is Restricted": "皮肤接触珠宝部件镍释放受限",
    "Novel Foods Require Efsa Approval": "新型食品需EFSA批准",
    "Nutrition And Health Claims Must Comply With EU Regulation": "营养和健康声明需符合欧盟法规",
    "Nutrition Labels Must Comply With NLEA Regulations": "营养标签需符合NLEA法规",
    "Pacifiers Must Comply With FDA Regulations": "奶嘴需符合FDA法规",
    "Pet Food Must Comply With FDA Regulations": "宠物食品需符合FDA法规",
    "Philippine Bureau Of Product Standards Product Quality Mark": "菲律宾产品标准局质量标志",
    "Philippine FDA Food Safety Registration": "菲律宾FDA食品安全注册",
    "Philippine Food And Drug Food Medical Devices Cosmetics": "菲律宾FDA食品/医疗器械/化妆品",
    "Philippine Toy Safety Standard": "菲律宾玩具安全标准",
    "Physical Mechanical Flammability And Chemical Performance Testing": "物理/机械/阻燃/化学性能测试",
    "Plant Protection Products Require EU Approval": "植物保护产品需欧盟批准",
    "Pots Tableware Kitchen Tools Require FDA Food Grade Certification": "锅具餐具厨具需FDA食品级认证",
    "Precious Metal Purity Marking E G 14k 18k 925 Silver": "贵金属纯度标记(如14k/18k/925银)",
    "Printing Inks Must Comply With REACH SVHC Restrictions": "印刷油墨需符合REACH SVHC限制",
    "Product Must Have Permanent Traceability Label Production Date Batch Manufacturer Info": "产品需有永久追溯标签(生产日期/批次/制造商信息)",
    "Products For Children Require CPC": "儿童产品需CPC",
    "Publishers Must Ensure Product Descriptions And Labels Comply With FTC Regulations": "出版商需确保产品描述和标签符合FTC法规",
    "Quality Control Mark For Certain Regulated Products": "部分管制产品质量控制标志",
    "Restriction Of Hazardous Substances Lead Mercury Cadmium Etc In Electrical And Electronic Equipment": "电气电子设备中有害物质限制(铅/汞/镉等)",
    "Society Of Automotive Engineers Standard (Non-Mandatory But Recommended": "SAE标准(非强制但推荐)",
    "Soil Fertilizer May Contain Heavy Metals Requiring Warning": "土壤肥料可能含需警告的重金属",
    "South African Bureau Of Standards Mandatory For Electronics Toys Building Materials": "南非标准局(电子/玩具/建材强制)",
    "Standar Nasional Indonesia Mandatory For 70 Product Categories": "印尼国家标准(70类产品强制)",
    "Supplement Ingredients Must Comply With REACH": "补充剂成分需符合REACH",
    "Supplements May Contain Ingredients Requiring Warning": "补充剂可能含需警告的成分",
    "Surface Coating Lead 90ppm Substrate Lead 100ppm": "表面涂层铅90ppm基材铅100ppm",
    "Textile Dyes And Auxiliaries Must Comply With REACH": "纺织染料和助剂需符合REACH",
    "Thai FDA Cosmetic Product Registration": "泰国FDA化妆品注册",
    "Thai FDA Food Registration": "泰国FDA食品注册",
    "Thai FDA Registration": "泰国FDA注册",
    "Thai Industrial Standards Institute Mandatory For 40 Product Categories": "泰国工业标准研究所(40类产品强制)",
    "Thai Toy Safety Standard": "泰国玩具安全标准",
    "Thailand Food And Drug Administration Food Cosmetics Medical Devices": "泰国FDA食品/化妆品/医疗器械",
    "Toy CE Certification Requires EU Authorized Representative": "玩具CE认证需欧盟授权代表",
    "Toy Materials Must Not Contain SVHC Substances Of Very High Concern": "玩具材质不得含SVHC高度关注物质",
    "Toy Safety European Standard Part 1 Mechanical Part 2 Flammability Part 3 Chemical": "玩具安全欧洲标准(第1部分机械/第2部分阻燃/第3部分化学)",
    "Toys That May Enter The Mouth E G Baby Teether Must Comply With Food Hygiene Law": "可能入口的玩具(如牙胶)需符合食品卫生法",
    "Travel Locks Must Pass TSA Certification": "旅行锁需通过TSA认证",
    "UAE Requires Gold Purity Testing For Jewelry": "珠宝黄金纯度检测(UAE)",
    "UL 2601 1 Medical Electrical Equipment Safety Standard": "UL 2601-1 医用电气设备安全标准",
    "UL 2743 Lithium Battery": "UL 2743 锂电池",
    "UL Certification": "UL 认证",
    "UL Medical Electrical": "UL 医用电气",
    "US Department Of Transportation Certification Headlights Tires Etc": "美国交通部认证(车灯/轮胎等)",
    "Vietnam Ministry Of Health Food Safety Certification": "越南卫生部食品安全认证",
    "Vietnam Product Conformity Mark For Electronics And Industrial Goods": "越南电子和工业产品合格标志",
    "Warning Label Requirement For Products Containing Lead Phthalates And Other Hazardous Substances": "含铅/邻苯二甲酸盐和其他有害物质的产品警告标签要求",
    "Waste Electrical And Electronic Equipment Recycling Requirement Registration Required In The Country Of Sale": "废旧电气电子设备回收要求(销售国注册)",
    "Wireless Device Technical Standards Certification Required For Bluetooth Wifi Products": "蓝牙/WiFi产品需无线设备技术标准认证",
    "Wireless Planning Commission Wireless Devices": "无线规划委员会无线设备",
    "Wood Packaging Material ISPM 15 Fumigation Certificate": "木质包装材料ISPM 15熏蒸证书",
    "Wood Packaging Material ISPM 15 Treatment Certificate": "木质包装材料ISPM 15处理证书",
    
    # More translations for remaining keys
    "Aafco Pet Food Standard": "AAFCO 宠物食品标准",
    "Association Of American Feed Control Officials Standard": "美国饲料管理协会(AFCO)标准",
    "Australia New Zealand Compliance Mark Electrical Safety Emc": "澳新合规标志(电气安全/EMC)",
    "Australia New Zealand Toy Safety Standard": "澳新玩具安全标准",
    "Baby Bottles Plates Etc Require Food Grade Certification": "奶瓶/盘子等需食品级认证",
    "Baby Products That Enter The Mouth Or Contact Skin Require EN71 Chemical Testing": "入口或接触皮肤的婴幼儿用品需EN71化学检测",
    "Baby Strollers And Car Seats Must Pass Suffocation Prevention Testing": "婴儿推车和安全座椅需通过防窒息测试",
    "Battery Containing Products Must Comply With The New Battery Regulation Carbon Footprint Declaration Etc": "含电池产品需符合新电池法规(碳足迹声明等)",
    "Brazilian Automotive Electronics Certification": "巴西汽车电子认证",
    "Brazilian Certification For Wheeled Luggage": "巴西拉杆箱认证",
    "Brazilian Health Agency Cosmetic Product Notification": "巴西卫生机构化妆品备案",
    "Brazilian National Institute Of Metrology 50 Categories": "巴西国家计量院(50类目)",
    "Brazilian Product Labeling Requirements": "巴西产品标签要求",
    "Brazilian Safety Standards For Baby Products": "巴西婴幼儿用品安全标准",
    "Brazilian Safety Standards For Certain Sports Equipment": "巴西部分运动器材安全标准",
    "Brazilian Safety Standards For Glass And Ceramic Products": "巴西玻璃陶瓷产品安全标准",
    "Brazilian Telecommunications Wireless Radio Devices": "巴西电信无线设备",
    "Bureau Of Indian Standards For Toy Safety": "印度标准局玩具安全",
    "Bureau Of Indian Standards Mandatory For 60 Categories": "印度标准局(60类目强制)",
    "California Cosmetics Reporting Regulation": "加州化妆品报告法规",
    "California Energy Efficiency Certification Power Adapters Chargers Etc": "加州能效认证(电源适配器/充电器等)",
    "Canada Consumer Product Safety Act Toys Must Meet CCPSA Requirements": "加拿大消费品安全法(玩具需满足CCPSA要求)",
    "CE Certification Requires Designating An Authorized Representative Within The EU": "CE认证需指定欧盟授权代表",
    "Chemical Registration Evaluation Authorization And Restriction SVHC Substances Of Very High Concern": "化学品注册/评估/授权/限制(SVHC高度关注物质)",
    "Children S Books Must Meet CE Safety Standards": "儿童书籍需符合CE安全标准",
    "Children S Books Must Meet CPSIA Safety Standards": "儿童书籍需符合CPSIA安全标准",
    "Children S Clothing Requires Lead Content Testing If For Children Under 12": "12岁以下儿童服装需铅含量检测",
    "Children S Sleepwear Must Pass Flammability Testing 16 CFR 1610 1615 1616": "儿童睡衣需通过阻燃测试(16 CFR 1610/1615/1616)",
    "Children S Sports Equipment Requires CPC": "儿童运动器材需CPC",
    "Children S Stationery Must Meet EN71 Chemical Safety": "儿童文具需符合EN71化学安全",
    "Cosmetics Factory Must Register With FDA Ingredients Must Comply With Regulations": "化妆品工厂需FDA注册(成分需合规)",
    "Cosmetics Manufacturing Quality Management Standard": "化妆品制造质量管理标准",
    "Cosmetics May Contain Ingredients Requiring Warning": "化妆品可能含需警告的成分",
    "CPC Required If Product Is Marketed For Children Under 12": "面向12岁以下儿童的產品需CPC",
    "CPSIA Compliance Required If Product Is Marketed For Children Under 12": "面向12岁以下儿童的产品需CPSIA合规",
    "Decor Items With LED Battery Require KC Mark": "带LED电池的装饰品需KC标志",
    "Dietary Supplement Facilities Must Register With FDA": "膳食补充剂设施需FDA注册",
    "Dietary Supplement Health And Education Act Compliance": "膳食补充剂健康与教育法案合规",
    "Dietary Supplements Must Meet 21 CFR Part 111 GMP Standard": "膳食补充剂需符合21 CFR 111 GMP标准",
    "Different Sports Equipment Has Different ASTM Safety Standards": "不同运动器材有不同ASTM安全标准",
    "E Waste Management Rules": "电子废弃物管理法规",
    "Electrical Appliance And Material Safety Law Mandatory Certification Type A Diamond PSE And Type B Rectangle PSE": "电气设备和材料安全法(强制认证A类菱形PSE和B类矩形PSE)",
    "Electrical Equipment And Energy Efficiency Registration": "电气设备与能源效率注册",
    "Electrical Safety Certification Non-Mandatory But Amazon Recommended Boosts Conversion Rate": "电气安全认证(非强制但亚马逊推荐可提高转化率)",
    "Electromagnetic Compatibility Testing For All Electronic Devices Type A Industrial And Type B Consumer": "所有电子设备电磁兼容测试(A类工业/B类消费)",
    "Energy Efficiency Labeling For Certain Appliances": "部分电器能效标签",
    "Ensure Product Does Not Infringe Copyright": "确保产品不侵犯版权",
    "EU Automotive Safety Certification Headlights Tires Etc": "欧盟汽车安全认证(车灯/轮胎等)",
    "EU Cosmetics Registration And Ingredient Requirements": "欧盟化妆品注册和成分要求",
    "EU Food Grade Contact Material Regulation": "欧盟食品级接触材料法规",
    "EU General Food Safety Regulation": "欧盟通用食品安全法规",
    "EU Medical Device Regulation 2017 745": "欧盟医疗器械法规2017/745",
    "EUropean Pet Food Industry Federation Standard": "欧洲宠物食品工业联合会标准",
    "EUropean Safety Standard For Baby Strollers": "欧洲婴儿推车安全标准",
    "EUropean Sports Equipment Safety Standard": "欧洲运动器材安全标准",
    "Fiber Content And Country Of Origin Labeling": "纤维含量和原产国标签",
    "Fiber Content Country Of Origin And Care Instruction Label Compliance": "纤维含量/原产国/护理说明标签合规",
    "Food Products Must Register With Dubai Municipality": "食品需在迪拜市政注册",
    "Garden Product Materials Must Comply With REACH": "园艺产品材质需符合REACH",
    "Home Product Materials Must Comply With REACH": "家居产品材质需符合REACH",
    "Independent Communications Authority Wireless Devices": "独立通信管理局无线设备",
    "India Baby Product Safety Standards": "印度婴幼儿用品安全标准",
    "India Drug And Cosmetic Rules": "印度药品和化妆品法规",
    "India Pet Food Standards": "印度宠物食品标准",
    "Indonesia Ministry Of Communication Wireless Radio Devices": "印尼通信部无线设备",
    "Indonesian Food And Cosmetic Registration": "印尼食品和化妆品注册",
    "Indonesian Food And Drug Agency Food Beverages Cosmetics": "印尼食品药品监管局(食品/饮料/化妆品)",
    "Indonesian Toy Safety Standard": "印尼玩具安全标准",
    "Infocomm Media Development Authority Safety Certification For IT AV Equipment": "新加坡媒体发展局IT/AV设备安全认证",
    "Innovation Science And Economic Development Canada Certification Required For Wireless Devices": "加拿大创新科学和经济发展部(无线设备认证)",
    "Kitchenware May Contain Heavy Metals E G Cast Iron Pots": "厨具可能含重金属(如铸铁锅)",
    "Society Of Automotive Engineers Standard (Non-Mandatory But Recommended)": "SAE标准(非强制但推荐)",
}

# Apply mappings to i18n.ts
import re

with open(r'D:\qclaw\workspace-AI工程师\heguimao-deploy\frontend\src\lib\i18n.ts', 'r', encoding='utf-8') as f:
    content = f.read()

count = 0
for en_text, zh_text in compliance_map.items():
    # Find the key that has this en value
    pattern = rf'("(?:site\.compliance[^"]*)":\s*\{{\s*en:\s*"{re.escape(en_text)}",\s*zh:\s*"[^"]*"\s*\}})'
    match = re.search(pattern, content)
    if match:
        old = match.group(0)
        # Extract the key name
        key_match = re.match(r'"([^"]+)"', old)
        if key_match:
            key = key_match.group(1)
            new = f'"{key}": {{ en: "{en_text}", zh: "{zh_text}" }}'
            content = content.replace(old, new)
            count += 1

with open(r'D:\qclaw\workspace-AI工程师\heguimao-deploy\frontend\src\lib\i18n.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Translated {count} compliance keys')
