#!/usr/bin/env python3
"""Add missing i18n keys to i18n.ts."""
import sys
sys.stdout.reconfigure(encoding='utf-8')

filepath = r"D:\qclaw\workspace-AI工程师\heguimao-deploy\frontend\src\lib\i18n.ts"
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# Missing keys with EN/ZH translations
missing_keys = {
    "common.general": {"en": "General", "zh": "综合"},
    "common.market": {"en": "Market", "zh": "市场"},
    "common.product": {"en": "Product", "zh": "产品"},
    "common.us": {"en": "US", "zh": "美国"},
    
    "report.pdf_export_fail": {"en": "PDF export failed", "zh": "PDF 导出失败"},
    "report.share_copy_ok": {"en": "Copied!", "zh": "已复制！"},
    "report.share_fail": {"en": "Share failed", "zh": "分享失败"},
    "report.share_title": {"en": "Compliance Cat Report", "zh": "合规猫报告"},
    "report.total_req": {"en": "Total requirements", "zh": "总要求数"},
    "report.high_pri": {"en": "High priority", "zh": "高优先级"},
    "report.generated_by": {"en": "Generated by Compliance Cat", "zh": "由合规猫生成"},
    "report.ai_recs_tab": {"en": "AI Recommendations", "zh": "AI 推荐"},
    "report.checklist": {"en": "Compliance Checklist", "zh": "合规清单"},
    "report.market_prereqs_tab": {"en": "Market Prerequisites", "zh": "市场前置条件"},
    "report.action_plan_tab": {"en": "Action Plan", "zh": "行动计划"},
    "report.analyzing": {"en": "AI is analyzing product compliance risks...", "zh": "AI 正在分析产品合规风险..."},
    "report.ai_smart": {"en": "AI Smart Analysis", "zh": "AI 智能分析"},
    "report.auto_match": {"en": "Auto-matched based on product features", "zh": "根据产品特征自动匹配"},
    "report.priority": {"en": "Priority", "zh": "优先级"},
    "report.med_risk": {"en": "Medium Risk", "zh": "中等风险"},
    "report.high_risk": {"en": "High Risk", "zh": "高风险"},
    "report.total_items": {"en": "Total Items", "zh": "总项数"},
    "report.generating": {"en": "Generating...", "zh": "生成中..."},
    "report.no_data": {"en": "No compliance data available for this category and market", "zh": "该品类和市场暂无合规数据"},
    "report.return_home": {"en": "Return Home", "zh": "返回首页"},
    "report.priority_note": {"en": "These items have the biggest impact", "zh": "这些项目影响最大"},
    "report.recommended_note": {"en": "Improve compliance completeness", "zh": "提升合规完整性"},
    "report.optional": {"en": "Optional", "zh": "可选"},
    "report.optional_note": {"en": "Depends on your product", "zh": "视产品而定"},
    "report.download_pdf": {"en": "Download Report (PDF)", "zh": "下载报告 (PDF)"},
    "report.share": {"en": "Share Report", "zh": "分享报告"},
    "report.view_appeal": {"en": "View Appeal Guide", "zh": "查看申诉指南"},
    "report.send_email": {"en": "Send Report via Email", "zh": "通过邮件发送报告"},
    "report.send_email_desc": {"en": "Opens your default email client with the report summary pre-filled", "zh": "会用默认邮件客户端打开报告摘要"},
    "report.sending": {"en": "Sending", "zh": "发送"},
    "report.sent": {"en": "Sent", "zh": "已发送"},
    "report.open_email": {"en": "Open Email Client", "zh": "打开邮件客户端"},
    "report.email_sent_hint": {"en": "Email client opened! Complete and send the email manually.", "zh": "已打开邮件客户端！请手动完成发送。"},
    "report.no_cat_warn": {"en": "No category selected, using general data", "zh": "未选择品类，使用通用数据"},
    "report.market_risks": {"en": "Market Prerequisites & Business Risks", "zh": "市场前置条件与商业风险"},
    "report.corp_risks": {"en": "Corporate Entity Risks", "zh": "企业实体风险"},
    "report.eori_num": {"en": "EORI Number", "zh": "EORI 编号"},
    "report.eori_desc": {"en": "Required for customs. Apply via national tax authority.", "zh": "海关必需。通过国家税务机关申请。"},
    "report.vat_desc": {"en": "Mandatory. Register in each target country", "zh": "强制注册。在每个目标国家注册"},
    "report.epr_desc": {"en": "Extended Producer Responsibility by product type", "zh": "按产品类型延伸生产者责任"},
    "report.eu_rep": {"en": "EU Authorized Rep", "zh": "欧盟授权代表"},
    "report.eu_rep_desc": {"en": "Required for CE marking. Must have physical EU address.", "zh": "CE 标志必需。必须有欧盟实体地址。"},
    "report.uk_vat_desc": {"en": "Required if turnover exceeds", "zh": "营业额超过需注册"},
    "report.uk_rp_desc": {"en": "Required for UKCA marking. Must be UK-based.", "zh": "UKCA 标志必需。必须英国本地。"},
    "report.uk_epr_desc": {"en": "New rules from 2025", "zh": "2025年起新规"},
    "report.us_reg": {"en": "US Business Registration", "zh": "美国商业注册"},
    "report.us_reg_desc": {"en": "EIN or SSN required for individual sellers", "zh": "个人卖家需要 EIN 或 SSN"},
    "report.us_addr": {"en": "US Physical Address", "zh": "美国实体地址"},
    "report.us_addr_desc": {"en": "P.O. Boxes not accepted", "zh": "不接受邮政信箱"},
    "report.sales_tax": {"en": "Sales Tax", "zh": "销售税"},
    "report.sales_tax_desc": {"en": "Nexus varies by state", "zh": "各州纳税义务不同"},
    "report.jp_tax": {"en": "Japanese Tax ID", "zh": "日本税务 ID"},
    "report.jp_tax_desc": {"en": "Required for cross-border sales", "zh": "跨境销售必需"},
    "report.consumers": {"en": "Consumer Affairs Registration", "zh": "消费者事务注册"},
    "report.consumers_desc": {"en": "Required for food, cosmetics", "zh": "食品化妆品必需"},
    "report.shell": {"en": "Shell Company", "zh": "空壳公司"},
    "report.shell_desc": {"en": "Amazon flags virtual offices", "zh": "亚马逊会标记虚拟办公室"},
    "report.name_match": {"en": "Name Matching", "zh": "名称一致性"},
    "report.name_desc": {"en": "Bank account, tax ID, and seller central name must match", "zh": "银行账户、税号和卖家中心名称必须一致"},
    "report.doc_verify": {"en": "Document Verification", "zh": "文件验证"},
    "report.doc_desc": {"en": "May request utility bills, bank statements", "zh": "可能要求水电账单、银行流水"},
    "report.lab_section": {"en": "Recommended Testing Laboratories", "zh": "推荐检测机构"},
    "report.cert_verify": {"en": "Certificate Verification Methods", "zh": "证书验证方式"},
    "report.lab_advice": {"en": "Choose labs accredited by ILAC-MRA", "zh": "选择 ILAC-MRA 认可的实验室"},
    "report.key_warn": {"en": "Key Warnings", "zh": "关键警告"},
    "report.action_plan": {"en": "Action Items & Plan", "zh": "行动项与计划"},
    "report.no_actions": {"en": "No action items available", "zh": "暂无行动项"},
    "report.high_priority": {"en": "High Priority", "zh": "高优先级"},
    "report.med_priority": {"en": "Medium Priority", "zh": "中优先级"},
    "report.low_priority": {"en": "Low Priority", "zh": "低优先级"},
    "report.immediate_action": {"en": "Immediate action required", "zh": "需立即行动"},
    "report.handle_soon": {"en": "Handle soon", "zh": "尽快处理"},
    "report.handle_order": {"en": "Handle in order", "zh": "依次处理"},
    "report.estimated_time": {"en": "Est. time", "zh": "预计时间"},
    "report.disclaimer_label": {"en": "Disclaimer", "zh": "免责声明"},
    "report.mandatory": {"en": "Mandatory", "zh": "强制"},
    "report.recommended": {"en": "Recommended", "zh": "推荐"},
    "report.table_cert": {"en": "Certification", "zh": "认证"},
    "report.table_type": {"en": "Type", "zh": "类型"},
    "report.table_level": {"en": "Level", "zh": "级别"},
    "report.table_reason": {"en": "AI Reason", "zh": "AI 理由"},
    "report.table_action": {"en": "Action", "zh": "行动"},
    "report.severity_high": {"en": "High", "zh": "高"},
    "report.severity_medium": {"en": "Medium", "zh": "中"},
    "report.severity_low": {"en": "Low", "zh": "低"},
    "report.ai_smart_title": {"en": "AI Smart Recommendations", "zh": "AI 智能推荐"},
    "report.recommended_actions": {"en": "Recommended actions", "zh": "推荐行动"},
    "report.high_risk_count": {"en": "High-risk mandatory items", "zh": "高风险强制项"},
    "report.banner_title": {"en": "Need a complete compliance guide?", "zh": "需要完整的合规指南？"},
    "report.banner_products": {"en": "PPWR Manual | CPSC eFiling Manual | Amazon Suspension Guide", "zh": "包装法手册 | CPSC eFiling 手册 | 亚马逊停售指南"},
    "report.banner_url": {"en": "Available on Payhip & Gumroad", "zh": "在 Payhip 和 Gumroad 可用"},
    "report.scan_qr": {"en": "Scan QR code or visit", "zh": "扫描二维码或访问"},
    
    # Lab descriptions
    "lab.sgs_desc": {"en": "Global leader, all certifications", "zh": "全球领先，全认证"},
    "lab.tuv_rheinland_desc": {"en": "Strong in EU/CE", "zh": "欧盟/CE 强项"},
    "lab.intertek_desc": {"en": "Wide coverage", "zh": "覆盖面广"},
    "lab.cti_desc": {"en": "China-based, competitive", "zh": "中国本土，性价比高"},
    "lab.bureau_veritas_desc": {"en": "Food/contact specialist", "zh": "食品/接触材料专家"},
    "lab.eurofins_desc": {"en": "Food/cosmetics", "zh": "食品/化妆品"},
    
    # Price labels
    "price.med_high": {"en": "Med-High", "zh": "中高"},
    "price.medium": {"en": "Medium", "zh": "中"},
    "price.low_med": {"en": "Low-Med", "zh": "低中"},
    "price.high": {"en": "High", "zh": "高"},
    
    # FCC/CE/CPC/PSE
    "report.fcc_id": {"en": "FCC ID", "zh": "FCC ID"},
    "report.verify_at": {"en": "Verify at", "zh": "验证于"},
    "report.ce_doc": {"en": "CE DoC", "zh": "CE 符合性声明"},
    "report.ce_v": {"en": "Verify notified body, EU Rep, applicable directives", "zh": "验证公告机构、欧盟代表、适用指令"},
    "report.cpc": {"en": "CPC", "zh": "CPC"},
    "report.cpc_v": {"en": "Verify CPSC-accepted lab", "zh": "验证 CPSC 认可实验室"},
    "report.pse": {"en": "PSE (Japan)", "zh": "PSE (日本)"},
}

# Find the closing brace of the translations object and insert before it
# Look for the last `};` that closes the translations
insert_marker = "};\n\n// Current locale state"
if insert_marker in content:
    for key, val in missing_keys.items():
        entry = f'  "{key}": {{ en: "{val["en"]}", zh: "{val["zh"]}" }},\n'
        content = content.replace(insert_marker, entry + insert_marker)
    print(f"Added {len(missing_keys)} keys before '// Current locale state'")
else:
    # Try alternate marker
    insert_marker2 = "};\n\n// Locale"
    if insert_marker2 in content:
        for key, val in missing_keys.items():
            entry = f'  "{key}": {{ en: "{val["en"]}", zh: "{val["zh"]}" }},\n'
            content = content.replace(insert_marker2, entry + insert_marker2)
        print(f"Added {len(missing_keys)} keys before '// Locale'")
    else:
        print("ERROR: Could not find insertion point")
        # Find where to insert
        lines = content.split('\n')
        for i, line in enumerate(lines[-20:]):
            print(f"  Last line {len(lines)-20+i}: {line[:80]}")

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Wrote {filepath}")
