#!/usr/bin/env python3
"""Find all hardcoded English strings in Report.tsx that need t() replacement."""
import re

filepath = r"D:\qclaw\workspace-AI工程师\heguimao-deploy\frontend\src\pages\Report.tsx"
content = open(filepath, encoding="utf-8").read()
lines = content.split("\n")

# Patterns to look for:
# 1. doc.text("...") — PDF text
# 2. alert("...") — alert dialogs
# 3. JSX text content: >English text<
# 4. className="..." strings that are labels
# 5. Template literal strings

hardcoded = []

for i, line in enumerate(lines):
    stripped = line.strip()
    
    # Skip import lines, type annotations, comments
    if stripped.startswith('import ') or stripped.startswith('//') or stripped.startswith('*'):
        continue
    if ': string' in stripped or ': number' in stripped or ': boolean' in stripped:
        continue
    
    # doc.text("...")
    for m in re.finditer(r'doc\.text\("([^"]+)"', line):
        hardcoded.append((i+1, "doc.text", m.group(1)))
    
    # alert("...")
    for m in re.finditer(r'alert\("([^"]+)"', line):
        hardcoded.append((i+1, "alert", m.group(1)))
    
    # JSX text content: >Text< (not inside {}, not className)
    # Look for >WORD< patterns that aren't inside {}
    # This is tricky; let's look for specific patterns
    if re.search(r'>{[^}]*"[A-Z][a-z]+ [A-Za-z ]+"[^}]*}<', line):
        # className with English words
        pass
    
    # Table head: [["Certification", "Type", ...]]
    for m in re.finditer(r'\[\["([^"]+)"', line):
        hardcoded.append((i+1, "table_header", m.group(1)))
    
    # shareText template with hardcoded strings
    if 'Compliance Cat Report' in stripped or 'Generated by Compliance Cat' in stripped:
        hardcoded.append((i+1, "share_text", stripped[:80]))

# Also check for hardcoded strings in JSX text nodes
# Pattern: >Text that looks like UI label< (not inside {})
jsx_patterns = [
    r'>AI Smart Recommendations<',
    r'>Compliance Checklist<',
    r'>Market Prerequisites<',
    r'>Action Plan<',
    r'>Detailed ',
    r'>All Categories<',
    r'>Recommended<',
    r'>Mandatory<',
    r'>High Risk<',
    r'>Med Risk<',
    r'>Total Items<',
    r'>Generating<',
    r'>No data available<',
    r'>Send via Email<',
    r'>Copy to Clipboard<',
    r'>Share Report<',
    r'>Disclaimer:',
    r'>Need a complete compliance guide?',
    r'>PPWR Manual',
    r'>CPSC eFiling Manual',
    r'>Available on Payhip',
    r'>Scan QR code or visit',
    r'>EORI Registration',
    r'>VAT Registration',
    r'>EPR Registration',
    r'>EU Representative',
    r'>UK VAT',
    r'>UK Responsible Person',
    r'>UK EPR',
    r'>US Product Liability Insurance',
    r'>US Agent/Address',
    r'>Sales Tax Collection',
    r'>Japan Consumption Tax',
    r'>Consumer Product Safety',
    r'>Corporate Name Mismatch',
    r'>Shell Company Risk',
    r'>Document Verification',
    r'>Lab Test Advice',
    r'>CE Certificate Validity',
    r'>FCC Certification Validity',
    r'>FDA Registration Validity',
    r'>Key Warning',
    r'>These items have the biggest impact',
    r'>Improve compliance completeness',
    r'>Estimated time',
    r'>Sending...',
    r'>Sent!',
    r'>Open Email Client',
    r'>Opens your default email client',
    r'>View Appeal Guide',
    r'>Recommended actions:',
    r'>High-risk mandatory items:',
]

print("=== JSX Text Node Patterns ===")
for pat in jsx_patterns:
    for i, line in enumerate(lines):
        if re.search(pat, line):
            print(f"Line {i+1}: {line.strip()[:150]}")

print("\n=== doc.text / alert / table_header ===")
for lineno, typ, text in hardcoded:
    print(f"L{lineno} [{typ}]: {text[:80]}")
