#!/usr/bin/env python3
"""
Replace ALL hardcoded English strings in Report.tsx with t() calls.
Also adds the i18n import.
"""
import re

filepath = r"D:\qclaw\workspace-AI工程师\heguimao-deploy\frontend\src\pages\Report.tsx"
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# Mapping of hardcoded strings to i18n keys
replacements = {
    # PDF exports (doc.text)
    '"Compliance Check Report"': '"report.pdf_title"',
    '"AI Smart Recommendations"': '"report.ai_smart_title"',
    
    # Table headers
    '"Certification"': '"report.table_cert"',
    '"Type"': '"report.table_type"',
    '"Level"': '"report.table_level"',
    '"AI Reason"': '"report.table_reason"',
    '"Action"': '"report.table_action"',
    
    # Alert messages
    '"PDF export failed. Please try again."': '"report.pdf_export_fail"',
    '"Report summary copied to clipboard!"': '"report.share_copy_ok"',
    '"Unable to share. Please try again."': '"report.share_fail"',
    
    # Share text
    '"🐱 Compliance Cat Report"': '"report.share_title"',
    '"Product:"': '"common.product"',
    '"Market:"': '"common.market"',
    '"Total requirements:"': '"report.total_req"',
    '"High priority:"': '"report.high_pri"',
    '"Generated by Compliance Cat - AI Compliance Checker"': '"report.generated_by"',
    
    # JSX text nodes - headings
    '">AI Smart Recommendations</h2>': '">{t("report.ai_smart_title")}</h2>',
    '">Market Prerequisites</h3>': '">{t("report.market_prereq")}</h3>',
    '">Detailed Compliance Checklist</h2>': '">{t("report.checklist")}</h2>',
    '">Action Plan</h2>': '">{t("report.action_plan")}</h2>',
    
    # Badge labels
    '">Recommended</span>': '">{t("report.recommended")}</span>',
    '">Mandatory</span>': '">{t("report.mandatory")}</span>',
    
    # Stats cards
    '">High Risk</p>': '">{t("report.high_risk")}</p>',
    '">Total Items</p>': '">{t("report.total_items")}</p>',
    
    # Prerequisites section
    '">EORI Registration:' + '"': '">{t("report.eori")}"',
    '">VAT Registration:' + '"': '">{t("report.vat")}"',
    '">EPR Registration:' + '"': '">{t("report.epr")}"',
    '">UK VAT:' + '"': '">{t("report.uk_vat")}"',
    '">UK Responsible Person:' + '"': '">{t("report.uk_rp")}"',
    '">UK EPR:' + '"': '">{t("report.uk_epr")}"',
    '">US Product Liability Insurance:' + '"': '">{t("report.us_insurance")}"',
    '">US Agent/Address:' + '"': '">{t("report.us_addr")}"',
    '">Sales Tax Collection:' + '"': '">{t("report.sales_tax")}"',
    '">Japan Consumption Tax:' + '"': '">{t("report.jp_tax")}"',
    '">Consumer Product Safety:' + '"': '">{t("report.consumers")}"',
    '">Shell Company:' + '"': '">{t("report.shell")}"',
    '">Document Verification:' + '"': '">{t("report.doc_verify")}"',
    '">Name Mismatch:' + '"': '">{t("report.name_match")}"',
    '">CE Certificate Validity:' + '"': '">{t("report.ce_v")}"',
    '">FCC Certification Validity:' + '"': '">{t("report.fcc_v")}"',
    '">FDA Registration Validity:' + '"': '">{t("report.fda_v")}"',
    '">Key Warning</h3>': '">{t("report.key_warn")}</h3>',
    
    # Disclaimer
    '">Disclaimer:' + '"': '">{t("report.disclaimer_label")}"',
    '">Need a complete compliance guide?' + '"': '">{t("report.banner_title")}"',
    '">PPWR Manual' + '"': '"report.ppwr_manual"',
    '">CPSC eFiling Manual' + '"': '"report.cpsc_manual"',
    '">Available on Payhip' + '"': '"report.available_on"',
    '">Scan QR code or visit' + '"': '"report.scan_qr"',
    
    # Lab advice
    '">Lab test results expiring within 6 months may not be accepted.' + '"': '"report.lab_advice"',
    
    # No data messages
    '">No data available.' + '"': '"report.no_data"',
    '">Generating recommendations...' + '"': '"report.generating"',
    
    # Priority notes
    '">These items have the biggest impact' + '"': '"report.priority_note"',
    '">Improve compliance completeness' + '"': '"report.recommended_note"',
    
    # Estimated time
    '">Est. time:' + '"': '"report.estimated_time"',
    
    # Email section
    '">Send via Email</h3>': '">{t("report.send_email")}</h3>',
    '">Copy to Clipboard</button>': '">{t("report.copy_clipboard")}</button>',
    '">Share Report</button>': '">{t("report.share")}</button>',
    
    # Breadcrumbs  
    '">All Categories</a>': '">{t("breadcrumb.category")}</a>',
    '">Select Market</a>': '">{t("breadcrumb.market")}</a>',
    
    # Category/subcategory display
    '">General"': '"common.general"',
    '">US"': '"common.us"',
}

# Apply simple string replacements
changed = 0
for old, new in replacements.items():
    if old in content:
        content = content.replace(old, new)
        changed += 1
        print(f"Replaced: {old[:60]} -> {new[:60]}")

print(f"\nTotal replacements: {changed}")

# Now add i18n import after the last import line
import_pattern = r'(import \{ store \} from "\.\./lib/store";\n)'
if re.search(import_pattern, content):
    content = re.sub(import_pattern, r'\1import { t } from "../lib/i18n";\n', content)
    print("Added i18n import")
else:
    print("WARNING: Could not find import location for i18n")

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)

print(f"\nDone. Wrote {filepath}")
